# Generated by Django 2.2.5 on 2021-05-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210326_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Value',
            new_name='value',
        ),
    ]
